### ISSUE TITLE
frr ./bootstrap fails the first pass through

### ISSUE THREAD

**Issue by nvsquirrel** [nvsquirrel/AWS-S2SVPN-Router#2]
currently, frr compile script fails on the first run of ./bootstrap with exit1. Current work around is I am running ./bootstrap.sh a second time.

**Comment by abruzzop** [comment]
sed '/AC_CONFIG_MACRO_DIR([m4])/a AC_CONFIG_AUX_DIR([.])' configure.ac

**Comment by nvsquirrel** [comment]
good call, I ended up adding `sed -i '/^AC_CONFIG_MACRO_DIR*/a AC_CONFIG_AUX_DIR([.])' configure.ac` and it's been merged into master.
